models/Client.php
<?php

namespace app\models;

use app\models\constants\UsersConstants;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "client".
 *
 * @property int $id
 * @property string $official_name Наименование
 * @property string $address Адрес
 * @property string $contact_person Контактное лицо
 * @property int $phone_number Телефон
 * @property string $email Email
 * @property string $bank_details_file Файл с реквизитами
 * @property int $countUsers Кол-во пользователей для клиента
 * @property int $contract_path Путь к файлу контракта
 *
 * @property ApparatusToClient[] $apparatusToClients
 * @property Contract $contract
 * @property Order[] $orders
 * @property Repairing[] $repairings
 * @property Users[] $users
 * @property ApparatusToClient[] $apparatusToClient Аппараты клиента
 */
class Client extends ActiveRecord
{
    public $apparatus_info;
    public $contract_path;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'client';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['address', 'contract_path'], 'string'],
            [['phone_number'], 'integer'],
            [['official_name', 'contact_person', 'email'], 'string', 'max' => 255],
            [['email'], 'email'],
            [['email', 'official_name'], 'unique'],
            ['bank_details_file', 'file'],
            [['official_name', 'email'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'official_name' => 'Наименование',
            'address' => 'Адрес',
            'contact_person' => 'Контактное лицо',
            'phone_number' => 'Телефон',
            'email' => 'Email',
            'bank_details_file' => 'Договор',
            'apparatus' => 'Аппараты',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApparatusToClients()
    {
        return $this->hasMany(ApparatusToClient::className(), ['client_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContract()
    {
        return $this->hasOne(Contract::className(), ['client_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['client_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRepairings()
    {
        return $this->hasMany(Repairing::className(), ['client_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(Users::className(), ['client_id' => 'id']);
    }

    /**
     * Загрузка файла с реквизитами
     */
    public function uploadBankDetails()
    {
        $form = new UploadForm();
        $form->scenario = $form::SCENARIO_DOCUMENT;

        $form->file = UploadedFile::getInstance($this, 'bank_details_file');

        if (!$form->file) {
            return false;
        }

        $tmp_name = 'contract';
        $target_dir = 'uploads/client/' . $this->id;

        if ($file_path = $form->upload($target_dir, $tmp_name, true)) {
            //Файл успешно загружен
            $this->bank_details_file = $file_path;
            if (!$this->save()) {
                Yii::error($this->errors, '_error');
            } else {
                return true;
            }
        } else {
            Yii::error($form->errors, '_error');
        }
        return false;
    }

    /**
     * Получает кол-во учетных записей для клиента
     * @return int
     */
    public function getCountUsers()
    {
        return Users::find()->andWhere(['client_id' => $this->id])->count();
    }

    /**
     * Создает пользователя системы для клиента
     * @return Users|bool
    //     * @throws \yii\base\Exception
     */
    public function createUser()
    {
        $password = rand(100000, 9999999);
        $user = new Users([
            'fio' => 'Пользователь ' . ($this->getCountUsers() + 1) . '. ' . $this->official_name,
            'role' => UsersConstants::ROLE_CLIENT,
            'login' => explode('@', $this->email)[0] . '_' . rand(100000, 9999999),
            'password' => $password,
            'client_id' => $this->id,
        ]);

        if (!$user->save()) {
            Yii::error($user->errors, '_errors');
            return false;
        }
        $user->open_password = $password;
        return $user;
    }

    /**
     * Получает аппараты для клиента
     */
    public function getApparatusList()
    {
        $sql = <<<SQL
            SELECT CONCAT(b.name, ' ', a.model, ' (', ac.serial_number, ')' ) AS apparatus_info  FROM apparatus_to_client ac
            LEFT JOIN apparatus a ON ac.apparatus_id = a.id
            LEFT JOIN brand b ON a.brand_id = b.id
SQL;
        $apparatus = [];
        /** @var ApparatusToClient $item */
        foreach (ApparatusToClient::findBySql($sql)->each() as $item) {
//            Yii::info($item->attributes, 'test');
            array_push($apparatus, $item->apparatus_info);
        }

        Yii::info($apparatus, 'test');

        return '<p style="font-size: 1rem;">' . implode('<br>', $apparatus) . '</p>';
    }

    public function getList()
    {
        return ArrayHelper::map(self::find()->all(), 'id', 'official_name');
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Client;
use Yii;
use app\models\Users;
use app\models\search\UsersSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;


class UsersController extends Controller
{

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return array|mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (Yii::$app->request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;

            $client = Client::findOne(Yii::$app->request->getQueryParam('client_id'));

            $dataProvider->query->andFilterWhere(['client_id' => $client->id]);

            return [
                'size' => 'large',
                'title' => 'Пользователи. ' . $client->official_name,
                'content' => $this->renderAjax('index', [
                    'searchModel' => null,
                    'dataProvider' => $dataProvider,
                ])
            ];
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return array|string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Пользователь",
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button('Закрыть',
                        ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Изменить', ['update', 'id' => $id],
                        ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * @return string
     */
    public function actionProfile()
    {
        return $this->render('profile', [
            'model' => Users::findOne(Yii::$app->user->identity->id),
        ]);
    }

    /**
     * @return array|string|Response
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Users();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                $model->uploadAvatar();
                return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
            } else {
                return [
                    'title' => "Создать нового пользователя",
                    'size' => "large",
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * @param $id
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        /** @var Users $model */
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                $model->uploadAvatar();
                return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];

            } else {
                return [
                    'title' => "Изменить пользователя",
                    'size' => "large",
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * @param $id
     * @return array
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionChange($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                $model->uploadAvatar();
                return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
            } else {
                return [
                    'title' => "Изменить пользователя",
                    'size' => "large",
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        }

        return [];
    }

    /**
     * @param $id
     * @return array|Response
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        if ($id != 1) {
            $model = Users::findOne($id);
        }
        if (file_exists('uploads/avatars/' . $model->avatar) && $model->avatar != null) {
            unlink('uploads/avatars/' . $model->avatar);
        }

        $model->delete();

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {

            return $this->redirect(['index']);
        }


    }

    /**
     * @return array|Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $model = $this->findModel($pk);
            if (file_exists('uploads/avatars/' . $model->avatar) && $model->avatar != null) {
                unlink('uploads/avatars/' . $model->avatar);
            }
            if ($pk != 1) {
                $model->delete();
            }
        }

        if ($request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {

            return $this->redirect(['index']);
        }

    }


    /**
     * @param $id
     * @return Users
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/client/_columns.php
<?php

use app\models\Client;
use app\models\constants\UsersConstants;
use yii\helpers\Html;
use yii\helpers\Url;

return [
//    [
//        'class' => 'kartik\grid\CheckboxColumn',
//        'width' => '20px',
//    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'official_name',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'contact_person',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'phone_number',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'email',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'label' => 'Информация',
        'content' => function(Client $model){
            $app_count = count($model->apparatusToClients ?? []);
            $user_count = $model->countUsers;
            return Html::a('Аппаратов: ' . $app_count, ['/apparatus-to-client/index', 'client_id' => $model->id], [
                'role' => 'modal-remote'
            ]) . '<br>' .
                Html::a('Пользователей: ' . $user_count, ['/users/index', 'client_id' => $model->id], [
                    'role' => 'modal-remote'
                ])  ;
        }
    ],
//    [
//        'class' => '\kartik\grid\DataColumn',
//        'content' => function (Client $model) {
//            $users_info = 'Пользователей: ' . $model->countUsers;
//            return $users_info . '<br>' . '<br>' . Html::a('Создать пользователя', ['create-user', 'id' => $model->id],
//                    [
//                        'class' => 'btn btn-info btn-sm',
//                        'role' => 'modal-remote',
//                        'data-confirm-title' => 'Вы уверены?',
//                        'data-confirm-message' => 'Подтвердите создание пользователя',
//                        'data-confirm-ok' => 'Создать',
//                        'data-confirm-cancel' => 'Отмена',
//                    ]);
//        }
//    ],

    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'template' => '{add_client}&nbsp;{add_apparatus} <br> {view} {update} {delete}',
        'urlCreator' => function ($action, $model, $key) {
            return Url::to([$action, 'id' => $key]);
        },
        'buttons' => [
            'add_apparatus' => function ($url, Client $model) {
                return Html::a('<i class="fa fa-plus"></i>', ['/apparatus-to-client/create', 'id' => $model->id], [
                    'title' => 'Добавить аппарат',
                    'data-toggle' => 'tooltip',
                    'role' => 'modal-remote'
                ]);
            },
            'add_client' => function ($url, Client $model) {
                return Html::a('<i class="fa fa-user"></i>', ['create-user', 'id' => $model->id], [
                    'title' => 'Добавить ползователя',
                    'data-toggle' => 'tooltip',
                    'role' => 'modal-remote',
                    'data-confirm-title' => 'Вы уверены?',
                    'data-confirm-message' => 'Подтвердите создание пользователя',
                    'data-confirm-ok' => 'Создать',
                    'data-confirm-cancel' => 'Отмена',
                ]);
            }

        ],
        'viewOptions' => ['role' => 'modal-remote', 'title' => 'Просмотр', 'data-toggle' => 'tooltip'],
        'updateOptions' => ['role' => 'modal-remote', 'title' => 'Редактировать', 'data-toggle' => 'tooltip'],
        'deleteOptions' => [
            'role' => 'modal-remote',
            'title' => 'Удалить',
            'data-confirm' => false,
            'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Are you sure?',
            'data-confirm-message' => 'Are you sure want to delete this item',
            'class' => UsersConstants::isSuperAdmin() ? '' : 'hidden'
        ],
    ],

];   

views/client/_form.php
<?php

use kartik\file\FileInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $form yii\widgets\ActiveForm */
/* @var $contract_model \app\models\Contract */

$file_info = [];
if (isset($file_information)) {
    $file_info = $file_information;
}

Yii::info($file_info, 'test');
?>

<div class="client-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'official_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </div>
    </div>


    <?= $form->field($model, 'address')->textarea(['rows' => 2]) ?>
    <div class="row">

        <div class="col-md-6">
            <?= $form->field($model, 'contact_person')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'phone_number')->textInput() ?>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <p>Информация о договоре</p>
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($contract_model, 'number')->textInput() ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($contract_model, 'date')->input('date') ?>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <?php
            try {
                echo $form->field($model, 'bank_details_file')->widget(FileInput::class, [
                    'options' => [
                        'multiple' => false,

                    ],
                    'pluginOptions' => [
                        'showCaption' => false,
                        'showRemove' => false,
                        'showUpload' => false,
                        'browseClass' => 'btn btn-primary btn-block',
                        'browseIcon' => '<i class="glyphicon glyphicon-open-file"></i> ',
                        'browseLabel' => $model->bank_details_file ? 'Выберите файл для замены' : 'Выберите файл',
                        'showPreview' => !$model->bank_details_file,
                        'uploadUrl' => Url::to(['@web/' . $model->bank_details_file]),
                        'initialPreview' => isset($file_info['path']) ? [$file_info['path']] : false,
                        'allowedFileExtensions' => ['doc', 'docx', 'txt', 'odt', 'pdf'],
                    ]
                ]);
            } catch (Exception $e) {
                Yii::error($e->getMessage(), '_error');
                echo $e->getMessage();
            } ?>
        </div>
    </div>
    <?= $form->field($model, 'contract_path')->hiddenInput()->label(false)->hint(false) ?>

    <?php if (!Yii::$app->request->isAjax) { ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update',
                ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/client/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $contract_model app\models\Contract */

?>
<div class="client-create">
    <?= $this->render('_form', [
        'model' => $model,
        'contract_model' => $contract_model,
    ]) ?>
</div>

views/client/index.php
<?php

use app\models\constants\UsersConstants;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ClientSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Клиенты';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);
$export = UsersConstants::isSuperAdmin() ? '{export}' : '';

?>
<div class="panel panel-inverse client-index">
    <div class="panel-heading">
        <div class="panel-heading-btn">
            <a href="javascript:" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
                        class="fa fa-expand"></i></a>
            <a href="javascript:" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i
                        class="fa fa-repeat"></i></a>
            <a href="javascript:" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i
                        class="fa fa-minus"></i></a>
        </div>
        <h4 class="panel-title">Клиенты</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?php
            try {
                echo GridView::widget([
                    'id' => 'crud-datatable',
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'tableOptions' => ['class' => 'table table-bordered'],
                    'pjax' => true,
                    'columns' => require(__DIR__ . '/_columns.php'),
                    'toolbar' => [
                        [
                            'content' =>
                                Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
                                    [
                                        'role' => 'modal-remote',
                                        'title' => 'Создать клиента',
                                        'class' => 'btn btn-default'
                                    ]) .
                                '{toggleData}' .
                                $export
                        ],
                    ],
                    'striped' => true,
                    'condensed' => true,
                    'responsive' => true,
                    'panel' => [
                        'headingOptions' => ['style' => 'display: none;'],
                        '<div class="clearfix"></div>',
                    ]
                ]);
            } catch (Exception $e) {
                Yii::error($e->getMessage(), '_error');
                echo $e->getMessage();
            } ?>
        </div>
    </div>
</div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/client/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $file_information array */
/* @var $contract_model \app\models\Contract */
?>
<div class="client-update">

    <?= $this->render('_form', [
        'model' => $model,
        'file_information' => $file_information,
        'contract_model' => $contract_model,
    ]) ?>

</div>

views/client/view.php
<?php

use app\models\Client;
use app\models\Contract;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $contract_model app\models\Contract */
?>
<div class="panel panel-inverse">
    <div class="panel-heading">
        Информация
    </div>
    <div class="panel-body">
        <?php
        try {
            echo DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'official_name',
                    'address:ntext',
                    'contact_person',
                    'phone_number',
                    'email:email',
//                    [
//                        'attribute' => 'bank_details_file',
//                        'value' => function (Client $model) {
//                            return Html::a(pathinfo($model->bank_details_file)['basename'],
//                                Url::to(['download', 'file' => $model->bank_details_file]));
//                        },
//                        'format' => 'raw'
//                    ],
                ],
            ]);
        } catch (Exception $e) {
            Yii::error($e->getMessage(), '_error');
            echo $e->getMessage();
        } ?>

    </div>
</div>
<?php if ($contract_model): ?>
    <div class="panel panel-inverse">
        <div class="panel-heading">
            Договор
        </div>
        <div class="panel-body">
            <?php
            if ($contract_model) {
                try {
                    echo DetailView::widget([
                        'model' => $contract_model,
                        'attributes' => [
                            'number',
                            'date:date',
                            [
                                'attribute' => 'contract_file',
                                'value' => function (Contract $model) {
                                    $client = $model->client;
                                    return Html::a(pathinfo($client->bank_details_file)['basename'],
                                        Url::to(['download', 'file' => $client->bank_details_file]));
                                },
                                'format' => 'raw',
                                'label' => 'Файл договора'
                            ]
                        ],

                    ]);
                } catch (Exception $e) {
                    Yii::error($e->getMessage(), '_error');
                    echo $e->getMessage();
                }
            }
            ?>
        </div>
    </div>
<?php endif; ?>