controllers/OrderController.php
<?php

namespace app\controllers;

use app\models\Apparatus;
use app\models\ApparatusToClient;
use app\models\constants\UsersConstants;
use app\models\Consumables;
use app\models\OrderToConsumables;
use app\models\Users;
use Yii;
use app\models\Order;
use app\models\search\OrderSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        /** @var Users $identity */
        $identity = Yii::$app->user->identity;

        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (UsersConstants::isAdmin()) {
            $dataProvider->query->andWhere(['<>', 'status', Order::STATUS_DRAFT])->andWhere([
                '<>',
                'status',
                Order::STATUS_DONE
            ]);
        } else {
            $dataProvider->query->andWhere(['client_id' => $identity->client_id]);
        }

        Yii::info('1212313', 'test');
        Yii::info(count($dataProvider->getModels()), 'test');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Заказ #" . $id,
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button('Закрыть',
                    ['class' => 'btn btn-default pull-right', 'data-dismiss' => "modal"])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Order model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the '_from_2' page.
     * @return mixed
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    public function actionCreate()
    {
        /** @var Users $identity */
        $identity = Yii::$app->user->identity;

        $request = Yii::$app->request;
        $model = new Order();
        $model->client_id = $identity->client_id;
        $order_to_cons = new OrderToConsumables();
        $order_to_cons_models = new OrderToConsumables(['order_id' => $model->id]);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Создание заказа.",
                    'size' => 'large',
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                        'order_to_cons' => $order_to_cons,
                        'order_to_cons_models' => $order_to_cons_models,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить черновик', [
                            'class' => 'btn btn-primary',
                            'type' => "submit",
                            'disabled' => true,
                            'id' => 'submit-order'
                        ])

                ];
            } else {
                if ($model->load($request->post())) {
                    Yii::info($model->attributes, 'test');
                    $model->uploadCountersPhoto();
                    if (!$model->save()) {
                        Yii::error($model->errors, '_error');
                        return [
                            'title' => "Создание заказа.",
                            'size' => 'large',
                            'content' => $this->renderAjax('create', [
                                'model' => $model,
                                'order_to_cons' => $order_to_cons,
                                'order_to_cons_models' => $order_to_cons_models,
                            ]),
                            'footer' => Html::button('Закрыть',
                                    ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                                Html::button('Сохранить черновик', [
                                    'class' => 'btn btn-primary',
                                    'type' => 'submit',
                                    'id' => 'submit-order'
                                ])
                        ];
                    }

                    //Добавляем расходники
                    $order_to_cons->load($request->post());
                    $order_to_cons->order_id = $model->id;
                    $order_to_cons->saveConsumables();

                    return [
                        'forceReload' => '#crud-datatable-pjax',
                        'forceClose' => true,
                    ];
                } else {
                    return [
                        'title' => "Создание заказа.",
                        'size' => 'large',
                        'content' => $this->renderAjax('create', [
                            'model' => $model,
                            'order_to_cons' => $order_to_cons,
                            'order_to_cons_models' => $order_to_cons_models,
                        ]),
                        'footer' => Html::button('Закрыть',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                            Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                    ];
                }
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'order_to_cons' => $order_to_cons,
                ]);
            }
        }

    }

    /**
     * Updates an existing Order model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        if (!UsersConstants::isAdmin() && $model->status != $model::STATUS_DRAFT) {
            throw new ForbiddenHttpException('Заявка не может быть отредактирована');
        }

        $order_to_cons_models = $model->orderToConsumables ?? null;
        if (!$order_to_cons_models) {
            $order_to_cons_models = new OrderToConsumables(['order_id' => $model->id]);
        }
        $order_to_cons = new OrderToConsumables();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Редактирование заказа #" . $id,
                    'size' => 'large',
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                        'order_to_cons' => $order_to_cons,
                        'order_to_cons_models' => $order_to_cons_models,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else {
                if ($model->load($request->post())) {
                    $model->uploadCountersPhoto();

                    if (!$model->save()) {
                        Yii::error($model->errors, '_error');
                        return [
                            'title' => "Редактирование заказа #" . $id,
                            'size' => 'large',
                            'content' => $this->renderAjax('update', [
                                'model' => $model,
                                'order_to_cons' => $order_to_cons,
                                'order_to_cons_models' => $order_to_cons_models,
                            ]),

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <!-- begin error -->
    <div class="error">
        <div class="error-code m-b-10"><?=$exception->statusCode?> <i class="fa fa-warning"></i></div>
        <div class="error-content">
            <div class="error-message"><?=$message?></div>
            <div class="error-desc m-b-20">
                Если это ошибка сервера. <br>
                Свяжитесь с тех поддержкой.
            </div>
            <div>
                <a href="/" class="btn btn-success">На главную</a>
            </div>
        </div>
    </div>
    <!-- end error -->

</div>

views/site/help.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Помощь';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-help">
    <h3>Service Desk. Система управления заявками покопийных контрактов</h3>
    <h4>Инструкция для работы пользователя.</h4>
    <p>&nbsp;</p>
    <p>Данная система предназначена для оптимизации взаимодействия клиентов, находящихся на покопийных контрактах с сервисной службой и позволяет клиенту выполнять следующие операции:</p>
    <p>- регистрировать инцидент (аппарат требует ремонта);</p>
    <p>- осуществлять заказ расходников;</p>
    <p>- фиксировать ежемесячные показания счетчиков.</p>
    <p>&nbsp;</p>
    <p><u>Раздел &laquo;Инцидент&raquo;</u></p>
    <p>Создание заявки на ремонт:</p>
    <ol>
        <li>Для создания заявки нажмите &laquo;<strong><?= Html::a('+', ['/repairing/create'], ['style' => 'font-size: 2rem;']); ?></strong></a>&raquo;</li>
        <li>Выберите модель аппарата</li>
        <li>Введите показания текущих счетчиков (Нужна помощь? Пишите на <a href="mailto:service@kcepokc.ru">service@kcepokc.ru</a>)</li>
        <li>Если у Вас проблема с качеством печати (полосы, грязь на отпечатке и пр) приложите, пожалуйста, скан отпечатка.</li>
        <li>Нажмите &laquo;Сохранить&raquo;. Вы можете отредактировать заявку или ее удалить</li>
        <li>Для отправки заявки в сервис-центр необходимо нажать &laquo;Отправить заявку&raquo;.</li>
    </ol>
    <p>После принятия заявки диспетчером её статус изменится на &laquo;В работе&raquo;. После выполнения на &laquo;Выполнено&raquo;.</p>
    <p>&nbsp;</p>
    <p><u>Раздел &laquo;Заказ РМ&raquo;</u></p>
    <p>Через систему Вы можете заказывать необходимые расходные материалы. Для монохромных аппаратов &ndash; тонер и барабан, для цветных &ndash; тонеры и барабаны CMYK.</p>
    <p>&nbsp;Создание заявки на расходные материалы:</p>
    <ol>
        <li>Для создания заявки нажмите &laquo;<strong><?= Html::a('+', ['/order/create'], ['style' => 'font-size: 2rem;']); ?></strong></a>&raquo;</li>
        <li>Выберите модель аппарата</li>
        <li>Введите показания текущих счетчиков. Обязательно необходимо приложить фотографию экрана с со счетчиком/ами (Нужна помощь? Пишите на <a href="mailto:service@kcepokc.ru">service@kcepokc.ru</a>)</li>
        <li>Нажмите &laquo;Сохранить черновик&raquo;. Вы можете отредактировать заявку или ее удалить</li>
        <li>Для отправки заявки в сервис-центр необходимо нажать &laquo;Отправить заявку&raquo;</li>
    </ol>
    <p>После принятия заявки диспетчером изменится ее статус на &laquo;В работе&raquo;. После выполнения на &laquo;Выполнено&raquo;.&nbsp;</p>
    <p>&nbsp;</p>
    <p><u>Раздел &laquo;Ежемесячные показания счетчиков&raquo;</u></p>
    <p>После 20-го каждого месяца клиент обязан предоставлять текущие показания счетчиков аппаратов, находящихся на обслуживании.</p>
    <p>&nbsp;</p>
    <p>Регистрация показаний счетчиков:</p>
    <ol>
        <li>Для создания отчета нажмите &laquo;<strong><?= Html::a('+', ['/report/create'], ['style' => 'font-size: 2rem;']); ?></strong></a>&raquo;</li>
        <li>Выберите модель аппарата</li>
        <li>Введите показания счетчика/ов</li>
        <li>Обязательно приложите фотографию экрана аппарата со счетчиком/ами</li>
        <li>Установить отчетный месяц и год</li>
        <li>Нажмите &laquo;Отправить&raquo;</li>
    </ol>
    <p>После подтверждения диспетчером статус отчета изменится на &laquo;Подтвержден&raquo;.</p>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Джест';
?>
    <!-- begin row -->
    <div class="row">
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-green">
                <div class="stats-icon"><i class="fa fa-desktop"></i></div>
                <div class="stats-info">
                    <h4>TOTAL VISITORS</h4>
                    <p>3,291,922</p>    
                </div>
                <div class="stats-link">
                    <a href="javascript:">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-chain-broken"></i></div>
                <div class="stats-info">
                    <h4>BOUNCE RATE</h4>
                    <p>20.44%</p>   
                </div>
                <div class="stats-link">
                    <a href="javascript:">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-purple">
                <div class="stats-icon"><i class="fa fa-users"></i></div>
                <div class="stats-info">
                    <h4>UNIQUE VISITORS</h4>
                    <p>1,291,922</p>    
                </div>
                <div class="stats-link">
                    <a href="javascript:">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-red">
                <div class="stats-icon"><i class="fa fa-clock-o"></i></div>
                <div class="stats-info">
                    <h4>AVG TIME ON SITE</h4>
                    <p>00:12:23</p> 
                </div>
                <div class="stats-link">
                    <a href="javascript:">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
    </div>
    <!-- end row -->
    <!-- begin row -->

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Авторизация';

$fieldOptions1 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];
?>
<div class="login login-v2">
    <!-- begin brand -->
    <div class="login-header" style="padding: 0;">
        <div class="brand">
            <span class="logo"></span> <?=Yii::$app->name?>
            <small>Введите данные для авторизации</small>
        </div>
        <div class="icon">
            <i class="fa fa-sign-in"></i>
        </div>
    </div>
    <!-- end brand -->
    <div class="login-content">
        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('login'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <div class="login-buttons">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
        </div>
        <div class="info-block" style="margin-top:1rem;">
            Забыли логин/пароль? <br> Напишите название организации и номер договора на <?= Html::a('service@kcepokc.ru', 'mailto:service@kcepokc.ru') ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/print.php
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="9" style=" text-align: left; font-size: 20px; padding-left: 10px;">ЛДСП</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">№ детали</th>
            <th  style=" text-align: center;padding:3px;">Цвет</th>
            <th  style=" text-align: center;padding:3px;">Толщина</th>
            <th  style=" text-align: center;padding:3px;">Длина</th>
            <th  style=" text-align: center;padding:3px;">Ширина</th>
            <th  style=" text-align: center;padding:3px;">Количество</th>
            <th  style=" text-align: center;padding:3px;">Кромка по длине</th>
            <th  style=" text-align: center;padding:3px;">Кромка по ширине</th>
            <th  style=" text-align: center;padding:3px;">Примечание</th>


        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">Материал заказчика</td>
            <td style=" text-align: left;padding:3px;">16</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">2</td>
            <td style=" text-align: left;padding:3px;">Нет - Нет</td>
            <td style=" text-align: left;padding:3px;">Нет - Нет</td>
            <td style=" text-align: left;padding:3px;">-</td>
        </tr>
    </tbody>
</table>
<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="6" style=" text-align: left; font-size: 20px; padding-left: 10px;">Оргалит</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">№ детали</th>
            <th  style=" text-align: center;padding:3px;">Цвет</th>
            <th  style=" text-align: center;padding:3px;">Длина</th>
            <th  style=" text-align: center;padding:3px;">Ширина</th>
            <th  style=" text-align: center;padding:3px;">Количество</th>
            <th  style=" text-align: center;padding:3px;">Примечание</th>


        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">Материал заказчика</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">2</td>
            <td style=" text-align: left;padding:3px;">-</td>
        </tr>
    </tbody>
</table>

<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="3" style=" text-align: left; font-size: 20px; padding-left: 10px;">Эскизы (общее количество)</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">Радиус 50-400 мм</th>
            <th  style=" text-align: center;padding:3px;">Радиус 450-1000 мм</th>
            <th  style=" text-align: center;padding:3px;">Прямоугольный выпил</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">3</td>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">1</td>
        </tr>
    </tbody>
</table>

<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="4" style=" text-align: left; font-size: 20px; padding-left: 10px;">Фрезеровка (общее количество)</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">Паз (м.п.)</th>
            <th  style=" text-align: center;padding:3px;">Четверть (м.п.)</th>
            <th  style=" text-align: center;padding:3px;">Наклонный пил (м.п.)</th>
            <th  style=" text-align: center;padding:3px;">Криволинейный пил (шт.)</th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">2</td>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">1</td>
        </tr>
    </tbody>
</table>

<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="3" style=" text-align: left; font-size: 20px; padding-left: 10px;">Присадка (общее количество)</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center; padding:3px;">1 - 10 мм</th>
            <th  style=" text-align: center; padding:3px;">11 - 20 мм</th>
            <th  style=" text-align: center; padding:3px;">21 - 35 мм</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left; padding:3px;">1</td>
            <td style=" text-align: left; padding:3px;">0</td>
            <td style=" text-align: left; padding:3px;">1</td>
        </tr>
    </tbody>
</table>