models/User.php
<?php

namespace app\models;

class User extends Users/*\yii\base\Object*/ implements \yii\web\IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['login' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return false;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
       return \Yii::$app->security->validatePassword($password, $this->password);
    }
}

models/Users.php
<?php

namespace app\models;

use app\models\constants\UsersConstants;
use app\models\query\UsersQuery;
use Yii;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $fio ФИО
 * @property int $role Роль
 * @property string $login Логин
 * @property string $password Пароль
 * @property string $password_reset_token
 * @property string $new_password Новый пароль
 * @property string $created_at
 * @property int $client_id Клиент
 * @property string $avatar Путь к аватару
 * @property UploadedFile $image Загружаемый файл
 * @property string $open_password Пароль показываемый админу при создании пользователя для клиента
 *
 * @property Client $client
 */
class Users extends ActiveRecord
{
    public $new_password;
    public $image;
    public $open_password;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['role', 'client_id'], 'integer'],
            [['created_at', 'image','password', 'new_password', 'open_password'], 'safe'],
            [['fio', 'login',  'password_reset_token', 'avatar'], 'string', 'max' => 255],
            [
                ['client_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Client::className(),
                'targetAttribute' => ['client_id' => 'id']
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fio' => 'ФИО',
            'role' => 'Роль',
            'login' => 'Логин',
            'password' => 'Пароль',
            'new_password' => 'Новый пароль',
            'password_reset_token' => 'Password Reset Token',
            'created_at' => 'Создан',
            'client_id' => 'Клиент',
            'avatar' => 'Аватар',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     * @throws \yii\base\Exception
     */
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->password = Yii::$app->security->generatePasswordHash($this->password);
        }

        if ($this->new_password != null) {
            $this->password = Yii::$app->security->generatePasswordHash($this->new_password);
        }
        return parent::beforeSave($insert);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }

    /**
     * {@inheritdoc}
     * @return UsersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UsersQuery(get_called_class());
    }

    public function getTypeDescription()
    {
        return UsersConstants::getString($this->role);
    }

    public function getRoles()
    {
        return UsersConstants::getArray();
    }

    public function getAvatar()
    {
        return UsersConstants::getImage($this->avatar);
    }

    /**
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     * @return bool
     */
    public function uploadAvatar()
    {
        $form = new UploadForm();
        $form->scenario = $form::SCENARIO_IMAGE;
        $form->file = UploadedFile::getInstance($this, 'image');
//        Yii::info($_FILES, 'test');
//        Yii::info($form->file, 'test');

        if ($form->file){
            $fileName = $form->upload('uploads/avatars', Yii::$app->security->generateRandomString());
            Yii::$app->db
                ->createCommand()
                ->update('users', ['avatar' => $fileName], ['id' => $this->id])
                ->execute();
        }

        return true;
    }

    /**
     * Сохраняет в файл инфу о пользователе
     * @return string Путь к файлу
     */
    public function saveInfo()
    {
        $info = [
            'Клиент: ' . $this->client->official_name ?? '',
            'ФИО: ' . $this->fio,
            'Логин: ' . $this->login,
            'Пароль: ' . $this->open_password,
        ];

        $dir = 'uploads/temp';
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        } else {
           $this->clearDir($dir);
        }

        $file_path = $dir . '/' . $this->id . 'userInformation.txt';

        $file = fopen($file_path, "a+");
        $text = implode(PHP_EOL, $info);
        flock($file, LOCK_EX);
        fwrite($file, $text);
        flock($file, LOCK_UN);
        fclose($file);

        return $file_path;
    }

    /**
     * Удаление всех файлов из папки
     * @param string $path_dir Путь к очищаемой папке
     * @return bool
     */
    private function clearDir($path_dir)
    {
        $files = array_diff(scandir($path_dir), ['..', '.', '.gitignore']);
        foreach ($files as $file_name){
            $file = $path_dir . '/' . $file_name;
            if (is_file($file)) {
                try {
                    unlink($file);
                } catch (\Exception $e) {
                    Yii::error($e->getMessage(), '_error');
                }
            }
        }
        return true;
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\Client;
use Yii;
use app\models\Users;
use app\models\search\UsersSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;


class UsersController extends Controller
{

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return array|mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (Yii::$app->request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;

            $client = Client::findOne(Yii::$app->request->getQueryParam('client_id'));

            $dataProvider->query->andFilterWhere(['client_id' => $client->id]);

            return [
                'size' => 'large',
                'title' => 'Пользователи. ' . $client->official_name,
                'content' => $this->renderAjax('index', [
                    'searchModel' => null,
                    'dataProvider' => $dataProvider,
                ])
            ];
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return array|string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Пользователь",
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button('Закрыть',
                        ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Изменить', ['update', 'id' => $id],
                        ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * @return string
     */
    public function actionProfile()
    {
        return $this->render('profile', [
            'model' => Users::findOne(Yii::$app->user->identity->id),
        ]);
    }

    /**
     * @return array|string|Response
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Users();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                $model->uploadAvatar();
                return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
            } else {
                return [
                    'title' => "Создать нового пользователя",
                    'size' => "large",
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * @param $id
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        /** @var Users $model */
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                $model->uploadAvatar();
                return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];

            } else {
                return [
                    'title' => "Изменить пользователя",
                    'size' => "large",
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * @param $id
     * @return array
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionChange($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                $model->uploadAvatar();
                return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
            } else {
                return [
                    'title' => "Изменить пользователя",
                    'size' => "large",
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        }

        return [];
    }

    /**
     * @param $id
     * @return array|Response
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        if ($id != 1) {
            $model = Users::findOne($id);
        }
        if (file_exists('uploads/avatars/' . $model->avatar) && $model->avatar != null) {
            unlink('uploads/avatars/' . $model->avatar);
        }

        $model->delete();

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {

            return $this->redirect(['index']);
        }


    }

    /**
     * @return array|Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $model = $this->findModel($pk);
            if (file_exists('uploads/avatars/' . $model->avatar) && $model->avatar != null) {
                unlink('uploads/avatars/' . $model->avatar);
            }
            if ($pk != 1) {
                $model->delete();
            }
        }

        if ($request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {

            return $this->redirect(['index']);
        }

    }


    /**
     * @param $id
     * @return Users
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/users/_columns.php
<?php

use app\models\constants\UsersConstants;
use app\models\Users;
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'client_id',
        'content' => function (Users $model) {
            return Html::a($model->client->official_name ?? '', ['/client/view', 'id' => $model->client->id ?? ''], [
                'role' => 'modal-remote'
            ]);
        }
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'avatar',
//        'filter' => false,
//        'contentOptions' => ['style'=>'width: 48px; height:48px;'],
//        'content' => function (Users $data) {
//         return Html::img($data->getAvatar(), [ 'style' => 'height:48px;width:48px; object-fit: cover;']);
//
//        },
//    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'fio',
        'content' => function (Users $model) {
            return Html::a($model->fio, ['/users/view', 'id' => $model->id], [
                'role' => 'modal-remote'
            ]);
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'login',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'role',
        'filter' => UsersConstants::getArray(),
        'content' => function (Users $data) {
            return $data->getTypeDescription();
        },
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'template' => '{update} {leadDelete}',
        'buttons' => [
            'leadDelete' => function ($url, $model) {
                if ($model->id != 1) {
                    $url = Url::to(['/users/delete', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                        'role' => 'modal-remote',
                        'title' => 'Удалить',
                        'data-confirm' => false,
                        'data-method' => false,// for overide yii data api
                        'data-request-method' => 'post',
                        'data-toggle' => 'tooltip',
                        'data-confirm-title' => 'Подтвердите действие',
                        'data-confirm-message' => 'Вы уверены что хотите удалить этого элемента?',
                        'class' => UsersConstants::isSuperAdmin() ? '' : 'hidden',
                    ]);
                }
                return false;
            },
        ],
        'urlCreator' => function ($action, $model, $key) {
            return Url::to([$action, 'id' => $key]);
        },
        'viewOptions' => ['role' => 'modal-remote', 'title' => 'Просмотр', 'data-toggle' => 'tooltip'],
        'updateOptions' => ['role' => 'modal-remote', 'title' => 'Изменить', 'data-toggle' => 'tooltip'],
        'deleteOptions' => [
            'role' => 'modal-remote',
            'title' => 'Удалить',
            'data-confirm' => false,
            'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Are you sure?',
            'data-confirm-message' => 'Are you sure want to delete this item'
        ],
    ],

];   

views/users/_form.php
<?php

use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var $model \app\models\Users */
?>

<div class="users-form">
    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
            <div id="image" class="col-md-12 text-center">
                <?= Html::img($model->getAvatar(), [
                    'style' => 'width:150px; height:150px;object-fit: cover;',
                    'class' => 'img-circle',
                ]) ?>
            </div>
            <div class="col-md-12" style="margin-top: 2rem;">
                <?php try {
                    echo $form->field($model, 'image')->widget(FileInput::class, [
                        'options' => [
                            'accept' => 'image/*',
                            'multiple' => false,
                            'class' => 'image_input',
                            'id' => 'inputFile',
                        ],
                        'pluginOptions' => [
                            'showPreview' => false,
                            'showCaption' => false,
                            'showRemove' => false,
                            'showUpload' => false,
                            'browseClass' => 'btn btn-primary btn-block btn-sm',
                            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
                            'browseLabel' => 'Выберите фото',
                            'allowedFileExtensions' => ['jpeg', 'jpg', 'png', 'gif'],
                        ]
                    ])->label(false);
                } catch (Exception $e) {
                    Yii::error($e->getMessage(), '_error');
                    echo $e->getMessage();
                } ?>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'role')->dropDownList($model->getRoles(), ['prompt' => 'Выберите роль']) ?>
                </div>
                <div class="col-md-6">
                    <?= $model->isNewRecord ? $form->field($model,
                        'password')->textInput(['maxlength' => true]) : $form->field($model,
                        'new_password')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>Пользователь клиента:&nbsp;<b><?= $model->client ? $model->client->official_name : '' ?></b></p>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<?php
$this->registerJs(<<<JS

$("#inputFile").on('change',function(e){
  var files = e.target.files;
    $.each(files, function(i,file){
        var reader = new FileReader();
        var image = $('#image');
        reader.readAsDataURL(file);
        reader.onload = function(e){
            var template = '<img style="object-fit: cover; width:150px; height:150px;" src="'+e.target.result+'" class="img-circle"> ';
            image.html('');
            image.append(template);
        };
    });
});
JS
);
?>

views/users/change.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
?>
<div class="users-update">

    <?= $this->render('change_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/change_form.php
<?php
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin([ 'options' => ['method' => 'post', 'enctype' => 'multipart/form-data']]); ?>
   
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'login')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'type')->dropDownList($model->getRoles(), ['prompt' => 'Выберите должность']) ?>
        </div>
        <div class="col-md-6">
            <?= $model->isNewRecord ? $form->field($model, 'password')->textInput(['maxlength' => true]) : $form->field($model, 'new_password')->textInput(['maxlength' => true]) ?>
        </div>
    </div>


    <?php ActiveForm::end(); ?>

</div>

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

?>
<div class="users-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/users/index.php
<?php

use app\models\constants\UsersConstants;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Пользователи";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);
$export =  UsersConstants::isSuperAdmin() ? '{export}' : '';

?>
<div class="panel panel-inverse user-index">
    <div class="panel-heading">
        <div class="panel-heading-btn">
            <a href="javascript:" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
                        class="fa fa-expand"></i></a>
            <a href="javascript:" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i
                        class="fa fa-repeat"></i></a>
            <a href="javascript:" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i
                        class="fa fa-minus"></i></a>
        </div>
        <h4 class="panel-title">Пользователи</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?php
            try {
                echo GridView::widget([
                    'id' => 'crud-datatable',
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'tableOptions' => ['class' => 'table table-bordered'],
                    'pjax' => true,
                    'columns' => require(__DIR__ . '/_columns.php'),
                    'toolbar' => [
                        [
                            'content' =>
                                Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
                                    [
                                        'role' => 'modal-remote',
                                        'title' => 'Создать клиента',
                                        'class' => 'btn btn-default'
                                    ]) .
                                '{toggleData}' .
                                $export
                        ],
                    ],
                    'striped' => true,
                    'condensed' => true,
                    'responsive' => true,
                    'panel' => [
                        'headingOptions' => ['style' => 'display: none;'],
                        '<div class="clearfix"></div>',
                    ]
                ]);
            } catch (Exception $e) {
                Yii::error($e->getMessage(), '_error');
                echo $e->getMessage();
            } ?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/users/profile.php
<?php

use app\models\User;
use yii\bootstrap\Modal;
use johnitvn\ajaxcrud\CrudAsset;
use yii\widgets\Pjax;

/** @var User $model */

$this->title = "Профиль";
$this->params['breadcrumbs'][] = $this->title;
CrudAsset::register($this);
$session = Yii::$app->session;
?>

<?php Pjax::begin(['enablePushState' => false, 'id' => 'crud-datatable-pjax']) ?>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7">
        <!-- CONTACT ITEM -->
        <div class="panel panel-default">
            <div class="panel-body profile">
                <div class="profile-image">
                    <img src="<?= $model->getAvatar() ?>" style=" width:120px; height:120px; object-fit: cover;"
                         alt="Пользователи">
                </div>
                <div class="profile-data">
                    <div class="profile-data-name"><?= $model->fio ?></div>
                    <div class="profile-data-title"><?= $model->getTypeDescription() ?></div>
                </div>
                <div class="profile-controls">
                    <a href="#" data-toggle="tooltip" class="profile-control-left" title="Уведомления"><span
                                class="fa fa-bell-o" data-pjax="0"></span></a>
                    <a href="/users/change?id=<?= $model->id ?>" data-toggle="tooltip" class="profile-control-right"
                       role="modal-remote" title="Изменить"><span class="fa fa-pencil"></span></a>
                </div>
            </div>
            <div class="panel-body">
                <div class="contact-info">
                    <p>
                        <small>Логин</small>
                        <br><b><?= $model->login ?></b></p>
                    <p>
                        <small>Пользователь Клиента:</small>
                        <br><b><?= $model->client->official_name ?? 'Клиент не найден';?></b></p>
                </div>
            </div>
        </div>
        <!-- END CONTACT ITEM -->
    </div>
</div>

<?php Pjax::end() ?>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "options" => [
        "tabindex" => false,
    ],
    "footer" => "",
]) ?>
<?php Modal::end(); ?>

views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
?>
<div class="users-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/view.php
<?php

use app\models\constants\UsersConstants;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
?>
<div class="users-view">
 
    <?php
    try {
        echo DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'fio',
                'login',
                [
                    'attribute' => 'open_password',
                    'label' => 'Пароль',
                    'visible' => $model->open_password ? true: false,
                ],
                [
                    'attribute' => 'role',
                    'value' => UsersConstants::getString($model->role)
                ],
            ],
        ]);
    } catch (Exception $e) {
        Yii::error($e->getMessage(), '_error');
        echo $e->getMessage();
    } ?>

</div>